### PR TITLE
feat/seo-updates

### PR DESCRIPTION
**Pull request by kempsterrrr**
This is a WIP PR that is addressing #214 - I'll be pushing updates to this as I go so folks can follow along and also allows for visual testing meta images etc. using https://metatags.io/

### CODE REVIEW

**Comment by Markkos89** [comment]
@kempsterrrr I just noticed this draft PR is pointing to `main`, can you please change it to `staging`? We are doing the following flow:

Work Branch ===> staging branch ===> main branch (production)

**Comment by kempsterrrr** [comment]
done @Markkos89 ✅

**Review by Markkos89 — APPROVED** [review]
Looks sharp! :rocket: Thanks a lot for the help here, Kemps!

We will have to add the `process.env.SITE_URL` to Vercel config right?

**Comment by kempsterrrr** [comment]
> We will have to add the `process.env.SITE_URL` to Vercel config right?

Vercel populates this automatically :)

> Vercel Environment variables that are automatically populated by the System, such as the URL of the Deployment or the name of the Git branch deployed.

**Pull request merged**
