### PR TITLE
feat: mvp fixes

### LINKED ISSUE #163: mvp: delete letter prefixes in quiz options
e.g., `A.`, `B.`, `C.` before each quiz answer

### PR DESCRIPTION
**Pull request by Markkos89**
## Changes

- changed open status for completed quizes
- deleted the method to show the Letter option on quiz options

this closes #163 and #164

Buttons
image
image
image

image
image
image

Modals
image
image
image
image

### CODE REVIEW

**Review by wolovim — COMMENTED** [review]
looking better on the quiz side! looks like some styling broke on the track index page though: 
Screenshot 2024-02-12 at 3 50 08 PM

**Comment by Markkos89** [comment]
> looking better on the quiz side! looks like some styling broke on the track index page though: Screenshot 2024-02-12 at 3 50 08 PM

hey Marc, that page is working properly to me:

image

Is there anything extra you did to make it break like that? So I can replicate it. Thanks

**Review by wolovim — APPROVED** [review]
another good iteration, cheers 🍻 

track index page bug exists on staging, so mustve been introduced in a prior PR. i expect you will see it by reducing your window width. i'll create a new issue.

**Comment by elPiablo** [comment]
Hey @Markkos89 
Cheers! But could you try opening up the tracks pages, and see what the cards look like? For me they are not rendering at an equal size, or predictable position.
bug-in-the-widths
stackingERC-20s

**Review by elPiablo — APPROVED** [review]
Really nice that you got those fixes done. Cheers!

**Comment by Markkos89** [comment]
I will gladly review your feedback, thanks for letting me know about this!

**Comment by wolovim** [comment]
@Markkos89 those styling bugs exist on staging and were not introduced in this PR, so feel free to merge this one and we can tackle those separately if you like. the issue is logged in #167. cc/ @elPiablo

**Pull request merged**
