### PR TITLE
feat: finish mobile scren for track details page

### PR DESCRIPTION
**Pull request by recepcankaya**
## Changes

- Mobile version of track details page finished
- Header changed and renamed it as navbar
- Footer is adjusted to mobile

## API Updates
- Collapsible component from shadcn was added through manual copy-paste

#39
#40

### CODE REVIEW

**Comment by Markkos89** [comment]
@recepcankaya can you update this branch with main latests version?

**Comment by recepcankaya** [comment]
With the latest commit, I updated the code as recommended by @Markkos89
- Made changes for navbar, track-details page and footer

**Comment by recepcankaya** [comment]
For `feat: finish the desktop version of track-details page` commit:
# Changes 
- Desktop version of track details page is finished. Later, it will be updated for the every screen will be made full responsive
- Toggle image is added onto header
- Even though it does not show very well, the images which are below are a clue of what it looks like in the desktop

image
image
image

**Review by Markkos89 — APPROVED** [review]
ready to go @recepcankaya 

if we see details after this we can fix them in later PRs :wink: 

thanks a lot for your hard work!

:rocket:

**Pull request merged**
