### PR TITLE
Feat/ui-adjustments

### PR DESCRIPTION
**Pull request by peteruche21**
some ui adjustment. based on @uma-l  s feedback.

still WIP

### CODE REVIEW

**Comment by Markkos89** [comment]
hey @peteruche21 nice work here! thank you :raised_hands: 

as a small comment could you change the name of the `exports` folder for a more representative one? or maybe just use the `public` folder from it's root.
another thing is the DS_Store file, if you could delete it :pray: 

thank mate!! Nice to ee you around :wink:

**Comment by peteruche21** [comment]
> hey @peteruche21 nice work here! thank you 🙌
> 
> as a small comment could you change the name of the `exports` folder for a more representative one? or maybe just use the `public` folder from it's root. another thing is the DS_Store file, if you could delete it 🙏
> 
> thank mate!! Nice to ee you around 😉

thanks mark, will remove exports folder once am through with it.

**Comment by wolovim** [comment]
havent dug in yet @peteruche21, but looking good at a quick glance. let me know when ready for another review 🤝

**Comment by Markkos89** [comment]
@peteruche21 at today's weekly meeting we were reviewing this PR and we took the following notes, I will address them if you don't mind.

- [ ] hide theme toggle button
- [ ] add/fix community icon on topbar
- [ ] update database card banner image for the new one (add the new one, it has been deleted)
- [ ] check fetching to backend issue (example: intro to eth)
- [ ] nice to have: add a "next leson" button as design
- [ ] fix mobile buttons styling for quiz modal as design
- [ ] hide cancel button on quiz modal
- [ ] update lesson's banner card images to the ones of their tracks card banner

cc: @wolovim @elPiablo @uma-l

**Comment by Markkos89** [comment]
> @peteruche21 at today's weekly meeting we were reviewing this PR and we took the following notes, I will address them if you don't mind.
> 
> * [ ]  hide theme toggle button
> * [ ]  add/fix community icon on topbar
> * [ ]  update database card banner image for the new one (add the new one, it has been deleted)
> * [ ]  check fetching to backend issue (example: intro to eth)
> * [ ]  nice to have: add a "next leson" button as design
> * [ ]  fix mobile buttons styling for quiz modal as design
> * [ ]  hide cancel button on quiz modal
> * [ ]  update lesson's banner card images to the ones of their tracks card banner
> 
> cc: @wolovim @elPiablo @uma-l

I created issues for each of the list item and sort them out on this project board to have more team vusialization.
any feedback or comment we have, let's try to place it there @wolovim @elPiablo @peteruche21 

I'm going to proceed to merge this PR and the others opened PRs to main, and then update the staging branch I just created so we are able to habe a more dynamic structure to handling tracks and lesson's visibility states across the different environments (production, stagging, and local).

**Review by Markkos89 — APPROVED** [review]

**Pull request merged**
