### PR TITLE
Feat/fundamentals page

### LINKED ISSUE #111: post-mvp: deduplicate content
when porting v1 content over to this repo, some content shared between lessons has been duplicated to ship the mvp. lets dedupe before fixes start to be applied in one place and not another. e.g., the solidity intro lesson is shared by the erc721 and erc20 tracks.

### PR DESCRIPTION
**Pull request by Markkos89**
## Changes

- created fundamentals page
- new bg_fundamentals.png image
- fetching fundamentals lessons hardcoding the path (because of some DB relationship we need)

image

this closes #111

_Note: After merging we need to edit all fundamentals lessons info on the database like lessonPath and more_

### CODE REVIEW

**Review by elPiablo — APPROVED** [review]
Looking very smart, Marcos. And really makes the user journey clearer and a much nicer experience. Cheers!! 
LFG!

**Review by wolovim — APPROVED** [review]
nice one 🥂 just need to remove the fundamentals track listing after this

**Comment by Markkos89** [comment]
- fixed quiz modal for mobile and desktop views
- changed next and previous buttons texts to right and left arrows

image

image

image

image

**Comment by elPiablo** [comment]
Nice work, @Markkos89 and @uma-l 🥮

**Pull request merged**
