### PR TITLE
feat: home page (desktop)

### LINKED ISSUE #27: feat: HomePage Page
For the time being, we have some key components to start building the HomePage page on the academy app of our project.
The design looks at follows:

image

figma design link: https://www.figma.com/file/YMEIW9uyNGNxtuy1R2tYyU/D_D-Academy-re-do?type=design&node-id=0-1&mode=design&t=1GnuKRa4jQqpvpvF-0

Some notes: 
- it doesn't show any scroll bar, but it should have. (There is one in the figma file that can be used)
- This is the HeroSection, and it has a "scroll down" button:
image
- Following we will have "banners section", which looks like this now (will have updates requested on this issue https://github.com/Developer-DAO/academy-turbo/issues/24 )
image
- And lastly, the footer, which looks like this now (it also will have small updates)
image

scrollbar design reference:
image

### PR DESCRIPTION
**Pull request by peteruche21**
created the home page UI.

requires #31

fixes #27

### CODE REVIEW

**Review by Markkos89 — APPROVED** [review]
@peteruche21 there is something wrong because the PR Preview link is looking like the styles didn't loaded:

image

image

image


approving because code-related it's more than good and we can fix anything in another update :wink: 
manage it at your will

thanks for the hard work my friend!!!! @peteruche21 :crown: :crown: 

:people_holding_hands:

**Comment by peteruche21** [comment]
I think it is a browser-related issue. it looks okay on my safari.

will switch to another PC and test with Firefox, chrome and Edge browsers later.

**Comment by okhaimie-dev** [comment]
> I think it is a browser-related issue. it looks okay on my safari.
> 
> will switch to another PC and test with Firefox, chrome and Edge browsers later.
> 
> edit: doesn't seem like a browser problem. will use another PC to work on this.

@peteruche21 I don't think it is a browser specific thing per say, some of the styling from the ui components stylesheet are missing in the academy app. 

You might want to reconfigure the `academy` repo to achieve an improved style on here. e.g. the bttf font file is missing in this repo so even though you are referencing it in the stylesheet, it is technically not possible for it to display properly on development or production preview this way. same goes with some other of the styles

**Comment by peteruche21** [comment]
Thanks @okhaimie-dev will look at how the styles, but do you think there is a possibility that the academy app specific styles overrides the one from ui package?

@Markkos89

**Comment by peteruche21** [comment]
I thought initially it was because I referenced styles of ui stylesheet inside academy stylesheet, but some components from ui package are losing styles totally.

**Comment by Markkos89** [comment]
> Thanks @okhaimie-dev will look at how the styles, but do you think there is a possibility that the academy app specific styles overrides the one from ui package?
> 
> @Markkos89

I believe that if you change the order of the styles file import on _app file to:

- first academy app local styles
- after ui package styles

it could work, could you try? @peteruche21  thanks mate!!!

**Comment by Markkos89** [comment]
@peteruche21 my bad, I merged one PR and it generated a conflict on this one. 

Could you pease resolve the conflict, please? Apologize mate :pray:

After that you can move forward to merge this! Thanks for the hard work!!! :muscle: 

:rocket:

**Pull request merged**
