### PR TITLE
feat: adding vercel analytics

### PR DESCRIPTION
**Pull request by Markkos89**
## Changes

- adding vercel analytics

### CODE REVIEW

**Review by elPiablo — APPROVED** [review]

**Comment by kempsterrrr** [comment]
As commented [here in discord](https://discord.com/channels/883478451850473483/1210586665093959690/1211441859872694373), before okaying such things please and we ensure the potential cost is discussed.

In this case, our sponsored Vercel Pro accounts gives us up to 25k events for free , after that it is 14 USD per 100k events:

image

Analytics was turned on for the old version of academy, in January the project recorded 1377 analytics events with 0 promotion for courses:

image

As we start to promote courses this number could expand rapidly so whilst I think it's fine for us to deploy this now we need to keep an eye on these numbers as it can get more expensive pretty quick and Academy at the min is pre-revenue. This highlights the importance of prioritising binging in money for this project.

For anything that requires a cost I'm happy to be the filter for OK'ing. Please make sure these points are considered before signing things off that might cost money in the future.

@elPiablo @Markkos89 @wolovim

**Comment by Markkos89** [comment]
Hey @kempsterrrr thank you for bringin this to the table and for the insights.
I up to change the analytics implementation to any other service of preference, mate! Really up to it. I just need the analytics, looking to Sentry and Hotjar to.

There is no rush to merge **this** PR if other option for analytics appears

**Comment by kempsterrrr** [comment]
I think it's fine to merge this at this moment in time as it's free. The main point I am making is the need to consider the cost before we introduce tooling or deploy things :)

Sentry and Hotjar as far as I understand solve different problems - error reporting and on page use tracking/analytics.

My suggestion would be merge this and then consider these alternative tools and open a separate issue for them with costs etc. considered

**Review by kempsterrrr — APPROVED** [review]

**Comment by kempsterrrr** [comment]
@Markkos89 feel free to merger this PR. Its important we have some analytics in place we just need to keep an eye on usage is all :)

**Pull request merged**
