### PR TITLE
chore: showing accounts registered as learners in homepage

### PR DESCRIPTION
**Pull request by Markkos89**
## Changes

- added ammount of registered learners on landing page as LearnWeb3.io has

image

the number is for staging environment accounts

### **Note: The glow effect can be changed as desired**

### CODE REVIEW

**Comment by wolovim** [comment]
(ignoring the design) social proof is good, but imo i wouldn't show off this number until its worth showing off 😅 idk where i'd draw the line - maybe a few hundred, if not 1k? just my first instinct

**Comment by kempsterrrr** [comment]
feedback similar to @wolovim here, eventually a positive feature and great idea, but for now, it might send a negative social signal that we have very few users for a learning platform compared with the competition.

**Comment by elPiablo** [comment]
> (ignoring the design) social proof is good, but imo i wouldn't show off this number until its worth showing off 😅 idk where i'd draw the line - maybe a few hundred, if not 1k? just my first instinct
> 
> would be nice to be able to see the number in the admin dashboard, though.

I tend to agree with these points @Markkos89 🌱

**Comment by Markkos89** [comment]
Yeah I thought the same, lol heheheh... I will close the pull request but leave the branch so I can rely on the code done later on.

Thank you guys!! @kempsterrrr @wolovim @elPiablo

**Pull request closed without merging**
