### PR TITLE
Staging to Main: v2 MVP release

### PR DESCRIPTION
**Pull request by Markkos89**
v2 MVP release

### CODE REVIEW

**Comment by elPiablo** [comment]
You must be tired of debugging at this stage, but there are still a couple of bugs when choosing a wallet:
I have zerion and MM browser extensions, but when I choose MM from Academy app, it returns the Zerion option only. Otherwise I have to force it manually to go to MM:

chooseMM-getZerion

the style of the 'send message' button is difficlut to see - as a result, it's easy to miss this step -which means getting acccess to and being able to do the quiz, but then your results won't get logged (I fell into this trap a few times already simply becasue of that button:
sendMessageButtonIsTooDifficultTooSee

**Comment by Markkos89** [comment]
> You must be tired of debugging at this stage, but there are still a couple of bugs when choosing a wallet: I have zerion and MM browser extensions, but when I choose MM from Academy app, it returns the Zerion option only. Otherwise I have to force it manually to go to MM:
> 
> chooseMM-getZerion
> 
> Obviosly, if MM is the only browser extension, it will choose MM.

And which would be the desired behaviour? 
Can you record a small video reproducing the issue?

As far I see in the screenshot, you choosed Metamask and it triggered the metamask extension. So there is nothing wrong there.

One thing to notice, is that if you have Zerion **and** metamask installed in your browser, by default, zerion starts _blocking_ metamakas extension. I don't know why, I don't know if this is intented or even if this is something "normal" between extensions but with my experience using it that was what I could notice and wanted to let you know so you might test it on your end too.

**Comment by elPiablo** [comment]
> > You must be tired of debugging at this stage, but there are still a couple of bugs when choosing a wallet: I have zerion and MM browser extensions, but when I choose MM from Academy app, it returns the Zerion option only. Otherwise I have to force it manually to go to MM:
> > 
> > chooseMM-getZerion
> > 
> > Obviosly, if MM is the only browser extension, it will choose MM.
> 
> And which would be the desired behaviour? 
I was only adding that as context

**Comment by elPiablo** [comment]
> One thing to notice, is that if you have Zerion **and** metamask installed in your browser, by default, zerion starts _blocking_ metamakas extension. I don't know why, I don't know if this is intented or even if this is something "normal" between extensions but with my experience using it that was what I could notice and wanted to let you know so you might test it on your end too.

I was thinking afterward our convo that it probably defaults to MM if we have imported the MM address into Zerion. 
So, new test: I'm going to create a new browser profile and a separate MM and a separate Zerion wallet and see how it behaves.

**Review by elPiablo — APPROVED** [review]
good to go!

**Pull request merged**
