### PR TITLE
feat: fixed quiz functionality and deleted unnused folder

### PR DESCRIPTION
**Pull request by Markkos89**
## Changes

- fixed quiz functionality 
- deleted unnused folder
- updated small quiz questions text details

### CODE REVIEW

**Review by peteruche21 — CHANGES_REQUESTED** [review]
checkpoint quiz question options are not clickable.

**Comment by Markkos89** [comment]
> checkpoint quiz question options are not clickable.

Thanks for noticing it!
It's fixed in the last commitm, please re-review :smiley:

**Review by peteruche21 — CHANGES_REQUESTED** [review]
checkpoint quiz options is bugged.

clicking multiple options does not de-select the previous selected option.

i think, only one option should be selectable except for multi-choice questions. i.e selecting another option de-selects the previously selected option.

**Comment by Markkos89** [comment]
> checkpoint quiz options is bugged.
> 
> clicking multiple options does not de-select the previous selected option.
> 
> i think, only one option should be selectable except for multi-choice questions. i.e selecting another option de-selects the previously selected option.

Hey @peteruche21 thanks for the feedback.
I tested it again and it works fine on my end, I recorded this small video to show it.
The first behaviour tested is the one you mentioned about not being able to de-select a previous selected answer in a multi-choice question.

https://vimeo.com/909557569/afe50bad5e

Let me know any update please, and thanks!

**Comment by peteruche21** [comment]
Oh okay, the current behavior in the video is what I actually meant.

I mean clicking on option (only one option can be selected at once in a given question)

Clicking on another option (same question) while there's a previous selection automatically deselects the already selected option and selects a new one.

Was it intended to be manually deselected like you did in the video?

**Review by peteruche21 — APPROVED** [review]

**Pull request merged**
