### PR TITLE
Feat/nft solidity track fixed fundamentals tracks imported

### PR DESCRIPTION
**Pull request by Markkos89**
## Changes

- fixed buil error by deleting old ContributorFooter component on markdown files breaking the build step
- imported nft-solidity track's lesson 2 _"Crafting a Basic NFT: A Step-by-Step ERC721 Tutorial for Beginners"_
- migrated all Fundamentals track's lessons from v1
- created and configured tracks folder's index.tsx file
- created and configured fundamentals folder's index.tsx file
- changed tracksArray name to a more descriptive one on all track's index file for **lessonsArray**
- configured url paths for all fundamentals lessons on fundamental's index page lessonArray
- added and configured new homepage screenshot for seo social media sharing image
- improved cards lists mobile responsive 
- removed unnused imports from markdown
- fixed quizzes path import
- added lessons public assets

---
_Already updated with latest `main` branch version_

### CODE REVIEW

**Review by recepcankaya — APPROVED** [review]

**Comment by Markkos89** [comment]
thanks a millon for the review @recepcankaya ! :raised_hands: 

@elPiablo waiting for your review in order to move forward with this. thanks in advance mate :pray: 

Let's keep it moving! :rocket:

**Comment by elPiablo** [comment]
Hey @Markkos89 

- sorry to hold you up on this,.It was quite a lot of commits to 'study' and stay concentrated, althought I've been dug in here for quite a few hours now!!  - I was wondering when you wrere going to give me a nudge jheje

- I followed your advice on Discord and checked all your changes. I'm getting a much better sense now of a lot (but not all) of the new architecture and directory structure/naming (at least inside the apps/academy directories). Thanks for that prompt.

- Also, I tested  all the side drawers they all look good in
-  the erc-20 track 
-  the nft-solidity tracks - however there is one **checkpoint quiz** that I could not check becuse it is in the side drawer called "Longer path. Learn abou JSON and IPFS" side drawer - that is in the **Crafting a Basic NFT.... ** lesson.

- there are no checkpoint questions appearing in **Intro to Ethereum, part 1** - there should be 3 in that one lesson (part 2 and part 3 don't have chekcpoint sidedrwarers yet)

Otherwise, amazing work. Good to go . I'll go and hit approve now 🥳

**Review by elPiablo — APPROVED** [review]
Hey @Markkos89 
- I followed your advice on Discord and checked all your changes. I got much better sense now of a lot (but not all) of the new architecture and directory structure (at least inside the apps/academy directories. Thanks for that prompt.

- And I did my best ever job to go meticulously through all the points you left on the PR. 
Good to go to Moon!!

**Comment by Markkos89** [comment]
`the nft-solidity tracks - however there is one checkpoint quiz that I could not check becuse it is in the side drawer called "Longer path. Learn abou JSON and IPFS" side drawer - that is in the **Crafting a Basic NFT.... ** lesson.`

I believe you are talking about `/apps/academy/src/pages/tracks/nft-solidity/2.mdx` 

What happens here is that the SideDrawer it's being doubled-used and it's not meant to be used that way:

This SideDrawer
image

Has another SideDrawer with an entire complete Lesson inside
image


And the checkpoint questions inside another SideDrawer inside the SideDrawer before closing it
image

Can we move forward someone and maybe fix it in future PRs? you can arrange them as you see better fit with more time :wink:

**Comment by Markkos89** [comment]
`however , there are no checkpoint questions appearing in Intro to Ethereum, part 1 - there should be 3 in that one lesson (part 2 and part 3 don't have checkpoint sidedrawers yet)`

I double checked this and there are some outdated changes needed to be added. Will push a commit now

In any case, I will merge the PR after that - We can continue iterating on this on https://github.com/Developer-DAO/academy-turbo/pull/59

Thank you @elPiablo :pray:

**Comment by elPiablo** [comment]
> Can we move forward someone and maybe fix it in future PRs? you can arrange them as you see better fit with more time 😉

Just for clarity, Marcos, are you saying that we should do this before or after MVP?

**Comment by Markkos89** [comment]
> > Can we move forward someone and maybe fix it in future PRs? you can arrange them as you see better fit with more time 😉
> 
> Just for clarity, Marcos, are you saying that we should do this before or after MVP?

I just edited my questions, there was a typo, my bad.

It was: _`Can we move forward  and maybe fix it in future PRs?`_

**Comment by elPiablo** [comment]
> It was: _`Can we move forward and maybe fix it in future PRs?`_

Before MVP launch, or after? Still not sure.

**Comment by Markkos89** [comment]
> > It was: _`Can we move forward and maybe fix it in future PRs?`_
> 
> Before MVP launch, or after? Still not sure 😄

Before

**Pull request merged**
