### PR TITLE
Feat/lesson info modal

### LINKED ISSUE #67: Change SideDrawer component using shadcn's Dialog component
figma url: https://www.figma.com/file/YMEIW9uyNGNxtuy1R2tYyU/D_D-Academy-re-do?type=design&node-id=0-1&mode=design&t=Ha3XLdrnvyiXqWDd-0

The v1 SideDrawer looks like this:
image

And has to be changed/updated to a Modal (using shadcn's Dialog component), to look like this:
image

The new InfoModal will host Questions components, so take a look at this please

### PR DESCRIPTION
**Pull request by recepcankaya**
## API Updates
- Add shadcn dialog component

### New Features *(required)*
- to test the new component, please open `tracks/intro-to-ethereum/1` 

`Fixes #67`
Will close issue #67  on merge

### CODE REVIEW

**Review by wolovim — COMMENTED** [review]
thanks for jumping in!

- first, looks like you need to rebase from `main` and resolve conflicts
- based on the image below, it seems that question titles arent displayed
- no styles are applied on selection of answer (or hover)
- question submit button color doesnt match figma
- form cancel button text and color are the same (unreadable) until you hover
Screenshot 2024-01-19 at 10 31 58 AM

**Comment by recepcankaya** [comment]
@wolovim i have seen a new component called `LessonInformationalModal` and mine is `LessonInfoModal`. I am confused rn. Are they supposed to do the same thing?

**Comment by wolovim** [comment]
damn. i think its the same @recepcankaya. @Markkos89 mentioned the QuestionsModal in this comment in #70, but the InformationalModal is created in the same PR:
> created new LessonQuestionsModal (cc @recepcankaya sorry for creating it, mate, I hope my code helps in the worst case)

github email notifications are noisy and can be easy to miss, so next time theres potential overlap like this, lets make sure a DM goes out @Markkos89.

looks like theres still at least a bit of styling to do from markko's component - the selected answer is unstyled, for example. to wrap up this unit of work, i suspect its quickest to abandon this component and finish the last of any styling from the `LessonInformationalModal`? sorry to see work get thrown out; lets tighten up communication to avoid that in the future.

**Comment by wolovim** [comment]
again, sorry to see this work rendered obsolete @recepcankaya. going to close this PR and encourage any new iterations start fresh from the latest on the `main` branch.

**Pull request closed without merging**
